-- 코드를 입력하세요
SELECT
    HOUR(DATETIME) AS 'HOUR',
    COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR(DATETIME);

-- HAVING 에는 select 절에 있는 컬럼명으로 기재
-- BETWEEN + AND 로 범위 지정