-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME
FROM ITEM_INFO
WHERE ITEM_ID IN
    (SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID ASC;

-- 코드를 작성해주세요
SELECT 
    T.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO AS I
    INNER JOIN 
    ITEM_TREE AS T
    USING(ITEM_ID)
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY T.ITEM_ID ASC;