-- SELECT
--     COUNT(*) AS FISH_COUNT,
--     MAX(LENGTH) AS MAX_LENGTH,
--     FISH_TYPE
-- FROM FISH_INFO AS F
--     JOIN
--     (SELECT
--         FISH_TYPE,
--         AVG(LENGTH) AS AVG_LENGTH
--     FROM FISH_INFO
--     GROUP BY FISH_TYPE) AS A
--     USING(FISH_TYPE)
-- WHERE A.AVG_LENGTH >= 33
-- GROUP BY FISH_TYPE;

-- 위에는 having 생각나기전! 멍충이 코드!

SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;

-- 이거 왜 틀려ㅠㅠ?