-- -- 코드를 입력하세요
-- SELECT
--     B.TITLE, B.BOARD_ID, 
--     R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
-- FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_REPLY AS R
--     USING(BOARD_ID)
-- WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
-- ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

-- 코드를 입력하세요
SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    SUBSTR(R.CREATED_DATE,1,10) AS CREATED_DATE
FROM USED_GOODS_BOARD AS B 
    RIGHT OUTER JOIN USED_GOODS_REPLY AS R
    USING(BOARD_ID)
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

-- DATE_FORMAT 말고 SUBSTR 사용!
-- INNER JOIN 대신 RIGHT OUTER JOIN 사용