-- 코드를 작성해주세요 (서브쿼리 참 좋아하죠?)
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN
    (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME IN ('BASS', 'SNAPPER'));

-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS I
    INNER JOIN 
    FISH_NAME_INFO AS N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME REGEXP ('^(BASS|SNAPPER)$');
