-- 코드를 입력하세요
SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_INS AS I
    JOIN
    ANIMAL_OUTS AS O
    USING (ANIMAL_ID)
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC;

-- WHERE DATEDIFF(O.DATETIME, I.DATETIME) < 0 : 날짜 간 차이. 시간 차이나면 0으로 계산되어 누락됨