-- -- 코드를 입력하세요
-- SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, 'NONE') AS 'TLNO'
-- FROM PATIENT
-- WHERE AGE <= 12 AND GEND_CD = 'W'
-- ORDER BY AGE DESC, PT_NAME ASC;

-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO  
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC;

-- IFNULL, COALESCE, NVL 함수는 NULL 값을 다른 값으로 대체하는 함수입니다.