-- 코드를 입력하세요
SELECT 
    PRODUCT_CODE,
    (PRICE * SUM_AMOUNT) AS SALES
FROM
    (SELECT
        P.PRODUCT_CODE, P.PRICE,
        SUM(O.SALES_AMOUNT) AS SUM_AMOUNT
    FROM PRODUCT AS P
        RIGHT OUTER JOIN
        OFFLINE_SALE AS O
        USING(PRODUCT_ID)
    GROUP BY product_id) AS T -- 별칭 붙여주기!!
ORDER BY 
    SALES DESC,
    PRODUCT_CODE ASC;