-- 3세대의 대장균의 ID(ID) 를 출력하는 SQL 문
-- 대장균의 ID 에 대해 오름차순 정렬
SELECT ID FROM ECOLI_DATA
WHERE PARENT_ID IN
    (SELECT ID FROM ECOLI_DATA
    WHERE PARENT_ID IN
        (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL) -- 2G
    ) -- 3G
ORDER BY 1;