-- 코드를 작성해주세요
SELECT 
    ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
WHERE NOT EXISTS (
    SELECT 1
    -- EXISTS/NOT EXISTS 서브쿼리에서는 SELECT 1처럼 상수 값을 쓰는 게 관례
    FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY ITEM_ID DESC;