-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT *
    FROM FIRST_HALF AS F LEFT OUTER JOIN ICECREAM_INFO AS I 
    USING(FLAVOR)) AS M
GROUP BY INGREDIENT_TYPE;

-- 코드를 입력하세요
SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
    INNER JOIN
    ICECREAM_INFO AS I
    USING(FLAVOR)
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;