-- 코드를 입력하세요
SELECT NAME, DATETIME 
FROM ANIMAL_INS
WHERE NOT EXISTS 
    (SELECT * FROM ANIMAL_OUTS
    WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID)
ORDER BY DATETIME ASC
LIMIT 3;

-- 코드를 입력하세요
SELECT
    NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE ANIMAL_ID IS NOT NULL
)
ORDER BY DATETIME ASC
LIMIT 3;

-- ANIMAL_OUTS에 NULL 값이 있다면 NOT IN 조건은 전부 거짓(False) 됨 주의!
