-- 코드를 입력하세요
SELECT 
    BOOK_ID, AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B LEFT OUTER JOIN  -- INNER JOIN 가능하니 생각해보기
    AUTHOR AS A USING(AUTHOR_ID)
WHERE CATEGORY = '경제'
--WHERE B.CATEGORY = '경제' 라고 별칭 사용하기
ORDER BY PUBLISHED_DATE;
-- ORDER BY B.PUBLISHED_DATE ASC 라고 별칭 사용하기;