-- -- 코드를 입력하세요
-- SELECT F.FLAVOR
-- FROM FIRST_HALF AS F LEFT OUTER JOIN ICECREAM_INFO AS I
--     USING(FLAVOR)
-- WHERE F.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE = 'fruit_based';

-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF AS HALF LEFT OUTER JOIN ICECREAM_INFO AS INFO USING(FLAVOR)
WHERE HALF.TOTAL_ORDER > 3000 
AND INFO.INGREDIENT_TYPE = 'fruit_based';
-- join에 별칭!!! 
-- on 이 아니라 using 
-- on을 사용해도 되는가?